# Generated by Django 5.0 on 2024-01-11 08:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0002_alter_shop_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=50, unique=True, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=90, unique=True, verbose_name="Название"),
        ),
    ]
