# Generated by Django 5.0 on 2024-01-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0004_alter_product_name_product_unique_product"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="product",
            name="unique_product",
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=90, unique=True, verbose_name="Название"),
        ),
    ]
