# Generated by Django 5.0 on 2024-01-11 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0005_remove_product_unique_product_alter_product_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parameter",
            name="name",
            field=models.CharField(max_length=50, unique=True, verbose_name="Название"),
        ),
    ]
