# Generated by Django 5.0 on 2024-01-14 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0008_alter_orderitem_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="backend.contact",
                verbose_name="Контакт",
            ),
        ),
    ]
