# Generated by Django 5.0 on 2024-01-23 08:12

import django.contrib.auth.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0009_alter_order_contact"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productinfo",
            options={
                "ordering": ("product", "shop"),
                "verbose_name": "Информация о продукте в магазине",
                "verbose_name_plural": "Список с информацией о продуктах",
            },
        ),
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(
                blank=True,
                error_messages={"unique": "A user with that username already exists."},
                max_length=150,
                null=True,
                unique=True,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                verbose_name="username",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product_info",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ordered_items_info",
                to="backend.productinfo",
                verbose_name="Информация о продукте",
            ),
        ),
    ]
