version: '3.9'

volumes:
  postgres_volume:
  static_volume:
  media_volume:

services:
  # Database Postgres
  db:
    image: postgres:latest
    container_name: postgres
    env_file:
      - ./retail_order_api/.env
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  # Django App
  web:
    build: ./retail_order_api
    container_name: retail_order_api
    ports:
      - "8000:8000"
    env_file:
      - ./retail_order_api/.env
    volumes:
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    depends_on:
      - db
    command: sh /usr/src/app/entrypoint.sh

  # web-server
  nginx:
      build: ./nginx
      container_name: nginx
      restart: on-failure
      ports:
        - '1337:80'
      volumes:
        - static_volume:/static
        - media_volume:/media
      depends_on:
        - web

  # Redis
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6300:6379"

  # Celery
  celery:
    build: ./retail_order_api
    command: celery -A retail_order_api worker -l info
    depends_on:
      - redis
      - db